version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=newuser
      - POSTGRES_PASSWORD=StrongPass123
      - POSTGRES_DB=newdb
      - SECRET_KEY=your_secret_key_here
      - CORS_ORIGINS=["http://localhost:3000"]
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=newuser
      - POSTGRES_PASSWORD=StrongPass123
      - POSTGRES_DB=newdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 